# Build stage, download base image for node
FROM public.ecr.aws/lambda/nodejs:16

LABEL maintainer="Thabang Zwane"

ARG FUNCTION_DIR="/var/task"

RUN export DEBIAN_FRONTEND=noninteractive

COPY package*.json ${FUNCTION_DIR}/

RUN npm install

COPY . ${FUNCTION_DIR}/

CMD [ "aws-lambda.api_handler" ]